### PR TITLE
Use spid-testenv-identityserver instead of idp.spid.gov.it

### PR DESCRIPTION
**Pull request by mlocati**
In the [README of the spid-testenv-docker repository](https://github.com/italia/spid-testenv-docker/blob/master/README.md) we say that we should use `spid-testenv-identityserver` for the test server name.

I'm pretty sure we should also update the files in [backoffice/certs](https://github.com/italia/spid-testenv-backoffice/tree/master/backoffice/certs) (`client-crt.pem` has `localhost` as Common Name).
Furthermore, [this certificate](https://github.com/italia/spid-testenv-backoffice/blob/621cbf39dc9c4615324a6315d75a53c5eee382bb/backoffice/src/components/ContentIdentityProvider/index.js#L51-L71) has `*.spid.gov.it` as Common name, and [this certificate](https://github.com/italia/spid-testenv-backoffice/blob/621cbf39dc9c4615324a6315d75a53c5eee382bb/backoffice/src/components/ContentIdentityProvider/index.js#L81-L90) has `localhost` as Common Name.

### CODE REVIEW

**Comment by mlocati** [comment]
I updated this pull request so that:
1. we have the correct https certificate for identity provider
2. fixing the identity provider metadata is very easy (just edit the `backoffice/idp_metadata/metadata-template.xml`)
3. there's now an URL where we have the the identity provider metadata XML

**Comment by giafar** [comment]
Hi @mlocati.
I had the same problem but I can confirm that it is not related to the certificate CN used for signing or encypting just because you can have whatever certificate you want. The CN is not related to the fqdn or whatever. 
I have update the entityID and the url in the backoffice identity provider xml metadata:
1. entityID: idp.spid.gov.it to spid-testenv-identityserver
1. Location: https://idp.spid.gov.it:9443/samlsso to https://spid-testenv-identityserver:9443/samlsso

The problem on my side is that shibboleth sp is not able to identify the identity provider because of issuer mismatch in the response and a security issue is raised.

**Comment by mlocati** [comment]
@giafar I'm 99% sure that if you change something in the sp metadata xml, it needs to be signed again (that's why in this pull request I generate the final metadata xml and sign it with xmlsectool)

**Comment by giafar** [comment]
Ciao @mlocati,
I know the xml has to be signed ;-)
In my Shibboleth SP configuration even if the validate attribute is true in the MetadataProvider section, there is no Signature MetadataFilter that checks the signature correctness: that's why it works. true just  validate the xml schema and is false by default on shibboleth
In the [example configuration](https://github.com/italia/spid-sp-shibboleth/blob/master/shibboleth2.xml), I know it is just an example, there is no Signature MetadataFilter: an italian SPID IDP should be trusted even not checking the signature ;-).
I wil test tomorrow an SP configuration with the signature filter and I'll keep you updated.

It is funny to have someone to talk with about such kind of issues.

Have a great day.

**Comment by mlocati** [comment]
In the commit https://github.com/italia/spid-testenv-backoffice/pull/24/commits/5ce688c065495d0998a29770861d42aa2e09153c I added the binary distribution of XmlSecTool.
It's about 10 MB of binary data: is this ok? Or should we download XmlSecTool dinamically instead of adding it to the repository?

**Comment by damikael** [comment]
Good job @mlocati! It would be perfect to download XmlSecTool dynamically during docker build.
Can you update this pull request with this change? 
Thanks

**Comment by mlocati** [comment]
> It would be perfect to download XmlSecTool dynamically during docker build.

Done in https://github.com/italia/spid-testenv-backoffice/pull/24/commits/593e405fa241c9d07e3586b49d82e9146ef07684

PS: if this PR will be merged, it'd be better to "Squash and merge" it, so that binary files previously added to this PR won't be included in the repository commit history.

**Comment by damikael** [comment]
Docker build fails during "Signing metadata... "
Error is "JAVA_HOME environment variable is not set."

@mlocati can you add java setup and set JAVA_HOME

Thanks

**Comment by mlocati** [comment]
Sure! Here it is: https://github.com/italia/spid-testenv-backoffice/pull/25

**Pull request merged**
